// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CongestionTaxDbContext))]
    [Migration("20251116071446_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Domain.Entities.TaxRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DailyMax")
                        .HasColumnType("numeric");

                    b.Property<int>("SingleChargeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "Year")
                        .IsUnique();

                    b.ToTable("TaxRules");
                });

            modelBuilder.Entity("Domain.Entities.TollFreeDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IncludeDayBefore")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TaxRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaxRuleId");

                    b.ToTable("TollFreeDates");
                });

            modelBuilder.Entity("Domain.Entities.TollFreeMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Month")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("TaxRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaxRuleId");

                    b.ToTable("TollFreeMonths");
                });

            modelBuilder.Entity("Domain.Entities.TollFreeVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaxRuleId")
                        .HasColumnType("uuid");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("TaxRuleId");

                    b.ToTable("TollFreeVehicles");
                });

            modelBuilder.Entity("Domain.Entities.TollFreeWeekday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TaxRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaxRuleId");

                    b.ToTable("TollFreeWeekdays");
                });

            modelBuilder.Entity("Domain.Entities.TollInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("TaxRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaxRuleId");

                    b.ToTable("TollIntervals");
                });

            modelBuilder.Entity("Domain.Entities.TaxRule", b =>
                {
                    b.HasOne("Domain.Entities.City", null)
                        .WithMany("TaxRules")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TollFreeDate", b =>
                {
                    b.HasOne("Domain.Entities.TaxRule", null)
                        .WithMany("TollFreeDates")
                        .HasForeignKey("TaxRuleId");
                });

            modelBuilder.Entity("Domain.Entities.TollFreeMonth", b =>
                {
                    b.HasOne("Domain.Entities.TaxRule", null)
                        .WithMany("TollFreeMonths")
                        .HasForeignKey("TaxRuleId");
                });

            modelBuilder.Entity("Domain.Entities.TollFreeVehicle", b =>
                {
                    b.HasOne("Domain.Entities.TaxRule", null)
                        .WithMany("TollFreeVehicles")
                        .HasForeignKey("TaxRuleId");
                });

            modelBuilder.Entity("Domain.Entities.TollFreeWeekday", b =>
                {
                    b.HasOne("Domain.Entities.TaxRule", null)
                        .WithMany("TollFreeWeekdays")
                        .HasForeignKey("TaxRuleId");
                });

            modelBuilder.Entity("Domain.Entities.TollInterval", b =>
                {
                    b.HasOne("Domain.Entities.TaxRule", null)
                        .WithMany("Intervals")
                        .HasForeignKey("TaxRuleId");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("TaxRules");
                });

            modelBuilder.Entity("Domain.Entities.TaxRule", b =>
                {
                    b.Navigation("Intervals");

                    b.Navigation("TollFreeDates");

                    b.Navigation("TollFreeMonths");

                    b.Navigation("TollFreeVehicles");

                    b.Navigation("TollFreeWeekdays");
                });
#pragma warning restore 612, 618
        }
    }
}
